### PR TITLE
Fix double escape on windows

### PR DESCRIPTION
**Pull request by max-mapper**
Removed the `"`

### CODE REVIEW

**Review by ChALkeR — APPROVED** [review]
An identical patch worked for me, but I didn't test this specific branch.

**Comment by ChALkeR** [comment]
Note: while this fixes the direct issue here, the logic on these lines doesn't seem entirely correct. I.e. what will happen if paths contain `'`?

**Comment by max-mapper** [comment]
@ChALkeR i dunno enough about windows to know what would happen

**Comment by ChALkeR** [comment]
For posterity, that concern is resolved in #3.

**Pull request merged**
